name: Strava sync EX

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  ELIXIR_VERSION: 1.14.0
  OTP_VERSION: 25
  DEBUG: "1"

jobs:
  sync-commit:
    name: Synchronize strava and commit new README (EX)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Strava sync
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        run: elixir strava_sync.ex

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Josep Lluis Giralt D'Lacoste
          author_email: josepgiraltdlacoste@gmail.com
          message: "Strava sync ${{ steps.date.outputs.date }}"
          add: "*.md"
